development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://bhorqtkkkawnxb:8727270dc1afdecec09df487268496f1349f48b692a3f71722ad13504500fd38@ec2-174-129-33-29.compute-1.amazonaws.com:5432/dlpf2vm39g9ni
  channel_prefix: nameofapp_production
